# 构建阶段
FROM qicfan/qms-build-base:beta AS builder
ARG APP_VERSION
ARG PUBLISH_DATE
ARG FANART_API_KEY
ARG DEFAULT_TMDB_ACCESS_TOKEN
ARG DEFAULT_TMDB_API_KEY
ARG DEFAULT_SC_API_KEY
ARG ENCRYPTION_KEY
# 设置工作目录
WORKDIR /app
# 复制项目文件
COPY . .
# 安装依赖
RUN go mod tidy
RUN echo $APP_VERSION
RUN echo $PUBLISH_DATE
# 构建应用
RUN CGO_ENABLED=0 go build -ldflags="-s -w -X 'main.Version=${APP_VERSION}' -X 'main.PublishDate=${PUBLISH_DATE}' -X main.FANART_API_KEY=${FANART_API_KEY} -X main.DEFAULT_TMDB_ACCESS_TOKEN=${DEFAULT_TMDB_ACCESS_TOKEN} -X main.DEFAULT_TMDB_API_KEY=${DEFAULT_TMDB_API_KEY} -X main.DEFAULT_SC_API_KEY=${DEFAULT_SC_API_KEY} -X main.ENCRYPTION_KEY=${ENCRYPTION_KEY}" -o QMediaSync .


# 运行阶段
FROM qicfan/qms-build-base:beta
# 设置时区
ENV TZ=Asia/Shanghai
ENV PATH=/app:$PATH
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=qms
ENV DB_PASSWORD=qms123456
ENV DB_NAME=qms
ENV DB_SSLMODE=disable

# 添加用户和组（推荐方式）
RUN addgroup -g 12331 qms && \
    adduser -D -u 12331 -G qms qms
# 验证用户创建
RUN id qms
# 配置免密码 sudo
RUN echo 'qms ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
# 创建共享内存目录
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm

# 设置工作目录
WORKDIR /app

# 创建必要的目录
COPY --from=builder /app/QMediaSync .
COPY web_statics ./web_statics/
COPY scripts ./scripts/
COPY assets/db_config.html ./web_statics/
COPY icon.ico .
RUN chmod +x /app/scripts/docker-entrypoint.sh
RUN chmod +x /app/scripts/watch_update.sh
RUN chmod +x /app/QMediaSync

VOLUME ["/app/config", "/media"]

# web ui端口
EXPOSE 12333
# 代理emby端口http
EXPOSE 8095
# 代理emby端口https
EXPOSE 8094
# 启动命令
CMD ["/app/scripts/docker-entrypoint.sh"]
